AllCops:
  Exclude:
    - 'bin/bundle'
    - vendor/bundle/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
